import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useAdmin } from './context';
import { Loader, ErrorBox, Empty, TableWrap, useToast } from './ui';
import { listInquiries, replyInquiryByEmail, updateInquiry, type Inquiry } from '../inquiryApi';
import './inquiry-crm.css';

const PAGE = 50;
const STATUS = [['new','新询盘'],['contacted','已联系'],['qualified','需求确认'],['quoting','报价中'],['quoted','已报价'],['won','成交'],['lost','丢失'],['invalid','无效'],['archived','归档']] as const;
const PRIORITY = [['high','高'],['medium','中'],['low','低']] as const;
const Icon = ({ children }: { children: React.ReactNode }) => <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>;
const I = {
  refresh:<Icon><path d="M20 11a8 8 0 0 0-14.9-4M4 5v5h5M4 13a8 8 0 0 0 14.9 4M20 19v-5h-5"/></Icon>,
  mail:<Icon><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></Icon>,
  check:<Icon><path d="m5 12 4 4L19 6"/></Icon>,
  clock:<Icon><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></Icon>,
  close:<Icon><path d="m6 6 12 12M18 6 6 18"/></Icon>,
};
const dt=(v:string)=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString();};
const dtInput=(v:string)=>{if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return '';const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;};
const statusLabel=(v:string)=>STATUS.find(x=>x[0]===v)?.[1]??v;
const priorityLabel=(v:string)=>PRIORITY.find(x=>x[0]===v)?.[1]??v;

export default function Inquiries(){
  const {lang}=useAdmin(); const zh=lang==='zh'; const toast=useToast();
  const [items,setItems]=useState<Inquiry[]>([]),[total,setTotal]=useState(0),[err,setErr]=useState<string|null>(null),[loading,setLoading]=useState(false);
  const [qInput,setQInput]=useState(''),[q,setQ]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[follow,setFollow]=useState('');
  const [limit,setLimit]=useState(PAGE),[selected,setSelected]=useState<Inquiry|null>(null),[saving,setSaving]=useState(false),[replying,setReplying]=useState(false),[replySubject,setReplySubject]=useState(''),[replyMessage,setReplyMessage]=useState('');
  const debounce=useRef<ReturnType<typeof setTimeout>|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const data=await listInquiries({limit,status,priority,follow:follow as ''|'today'|'overdue'|'upcoming',q});setItems(data.items??[]);setTotal(Number(data.total??0));setErr(null);}catch(e){setErr(String(e));}finally{setLoading(false);}},[limit,status,priority,follow,q]);
  useEffect(()=>{load();},[load]); useEffect(()=>()=>{if(debounce.current)clearTimeout(debounce.current)},[]);
  const onSearch=(v:string)=>{setQInput(v);if(debounce.current)clearTimeout(debounce.current);debounce.current=setTimeout(()=>{setQ(v);setLimit(PAGE)},300)};
  const clearFilters=()=>{setQInput('');setQ('');setStatus('');setPriority('');setFollow('');setLimit(PAGE)};
  const openDetail=(it:Inquiry)=>{setSelected(it);setReplySubject(`Re: #${it.id} ${it.equipment||'Inquiry'}`);setReplyMessage('')};
  const replied=useMemo(()=>items.filter(i=>i.replied===1).length,[items]);
  const due=useMemo(()=>items.filter(i=>i.follow_up_at&&new Date(i.follow_up_at).getTime()<Date.now()).length,[items]);
  const failed=useMemo(()=>items.filter(i=>i.mail_status==='failed').length,[items]);
  const patch=(p:Partial<Inquiry>)=>setSelected(v=>v?{...v,...p}:v);
  const saveDetail=async()=>{if(!selected)return;setSaving(true);try{await updateInquiry(selected.id,{lead_status:selected.lead_status,priority:selected.priority,source:selected.source,page_url:selected.page_url,notes:selected.notes,follow_up_at:selected.follow_up_at,last_contact_at:selected.last_contact_at,replied:selected.replied});setItems(v=>v.map(i=>i.id===selected.id?selected:i));toast.ok(zh?'询盘已保存':'Inquiry saved');}catch(e){toast.err(String(e));}finally{setSaving(false)}};
  const sendReply=async()=>{if(!selected||!replyMessage.trim())return;setReplying(true);try{const r=await replyInquiryByEmail(selected.id,replySubject.trim(),replyMessage.trim());if(!r.ok)throw new Error(r.error||r.status);const next={...selected,replied:1,last_contact_at:new Date().toISOString(),lead_status:selected.lead_status==='new'?'contacted':selected.lead_status};setSelected(next);setItems(v=>v.map(i=>i.id===next.id?next:i));setReplyMessage('');toast.ok(zh?'邮件已发送':'Email sent');}catch(e){toast.err(String(e));}finally{setReplying(false)}};

  return <div className="b2b-page inquiry-crm-page">
    <div className="inq-head"><div className="adm-head-text"><h2>{zh?'询盘中心':'Inquiry Center'}</h2><p className="adm-head-desc">{zh?'客户线索 · 销售阶段 · 跟进任务 · 邮件往来':'Leads · pipeline · follow-up · email communication'}</p></div><div className="adm-head-actions"><button className="admin-btn" onClick={load} disabled={loading}>{I.refresh}{loading?'…':(zh?'刷新':'Refresh')}</button></div></div>
    <section className="b2b-kpis inquiry-kpis"><div className="b2b-kpi"><span className="b2b-kpi-icon">{I.mail}</span><div className="b2b-kpi-label">TOTAL</div><div className="b2b-kpi-value">{total}</div><div className="b2b-kpi-note">{zh?'全部询盘':'All inquiries'}</div></div><div className="b2b-kpi"><span className="b2b-kpi-icon">{I.clock}</span><div className="b2b-kpi-label">FOLLOW UP</div><div className="b2b-kpi-value">{due}</div><div className="b2b-kpi-note">{zh?'待跟进 / 已逾期':'Due / overdue in view'}</div></div><div className="b2b-kpi"><span className="b2b-kpi-icon">{I.check}</span><div className="b2b-kpi-label">REPLIED</div><div className="b2b-kpi-value">{replied}</div><div className="b2b-kpi-note">{zh?'当前结果集':'Current result'}</div></div><div className="b2b-kpi"><span className="b2b-kpi-icon">{I.mail}</span><div className="b2b-kpi-label">MAIL FAIL</div><div className="b2b-kpi-value">{failed}</div><div className="b2b-kpi-note">{zh?'邮件异常':'Mail errors'}</div></div></section>
    <div className="inq-toolbar inquiry-crm-toolbar"><input className="inq-search" placeholder={zh?'搜索姓名 / 邮箱 / WhatsApp / 设备 / 留言…':'Search name / email / WhatsApp / equipment / message…'} value={qInput} onChange={e=>onSearch(e.target.value)}/><select className="admin-select inq-filter-select" value={status} onChange={e=>{setStatus(e.target.value);setLimit(PAGE)}}><option value="">{zh?'全部阶段':'All stages'}</option>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select><select className="admin-select inq-filter-select" value={priority} onChange={e=>{setPriority(e.target.value);setLimit(PAGE)}}><option value="">{zh?'全部优先级':'All priority'}</option>{PRIORITY.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select><select className="admin-select inq-filter-select" value={follow} onChange={e=>{setFollow(e.target.value);setLimit(PAGE)}}><option value="">{zh?'全部跟进':'All follow-up'}</option><option value="today">{zh?'今天':'Today'}</option><option value="overdue">{zh?'已逾期':'Overdue'}</option><option value="upcoming">{zh?'待跟进':'Upcoming'}</option></select>{(q||status||priority||follow)&&<button className="admin-btn" onClick={clearFilters}>{zh?'清除筛选':'Clear'}</button>}<span className="admin-count">{items.length} / {total}</span></div>
    {err&&<ErrorBox>{err}</ErrorBox>}
    {loading&&items.length===0?<Loader label={zh?'加载询盘…':'Loading inquiries…'}/>:items.length===0?<Empty text={zh?'暂无匹配询盘':'No matching inquiries'}/>:<TableWrap><table className="admin-table inquiry-crm-table"><thead><tr><th>ID</th><th>{zh?'客户':'Customer'}</th><th>{zh?'设备':'Equipment'}</th><th>{zh?'阶段':'Stage'}</th><th>{zh?'优先级':'Priority'}</th><th>{zh?'跟进':'Follow-up'}</th><th>{zh?'邮件':'Mail'}</th><th></th></tr></thead><tbody>{items.map(it=><Fragment key={it.id}><tr className={selected?.id===it.id?'is-selected':''} onClick={()=>openDetail(it)}><td><code>#{it.id}</code></td><td><div className="b2b-row-title">{it.customer_name||'—'}</div><div className="b2b-row-sub">{it.email||it.whatsapp||it.country||'—'}</div></td><td><div className="b2b-row-title">{it.equipment||'—'}</div><div className="b2b-row-sub">{it.source||'website'}</div></td><td><span className={`crm-pill stage-${it.lead_status||'new'}`}>{statusLabel(it.lead_status||'new')}</span></td><td><span className={`crm-priority priority-${it.priority||'medium'}`}>{priorityLabel(it.priority||'medium')}</span></td><td>{it.follow_up_at?<span className={new Date(it.follow_up_at).getTime()<Date.now()?'crm-overdue':''}>{dt(it.follow_up_at)}</span>:<span className="admin-muted">—</span>}</td><td><span className={`inq-badge inq-badge-${it.mail_status==='sent'?'ok':it.mail_status==='failed'?'bad':'muted'}`}>{it.mail_status==='sent'?(zh?'已发':'Sent'):it.mail_status==='failed'?(zh?'失败':'Failed'):it.mail_status==='skipped'?(zh?'未配置':'Skipped'):(zh?'待发':'Pending')}</span></td><td>›</td></tr></Fragment>)}</tbody></table></TableWrap>}
    {items.length<total&&<div className="inquiry-load-more"><button className="admin-btn" disabled={loading} onClick={()=>setLimit(v=>v+PAGE)}>{zh?'加载更多':'Load more'}</button></div>}
    {selected&&<div className="inq-drawer-overlay" onClick={()=>setSelected(null)}><aside className="inq-drawer" onClick={e=>e.stopPropagation()}><header className="inq-drawer-head"><div><div className="inq-drawer-kicker">INQUIRY #{selected.id}</div><h3>{selected.customer_name||'—'}</h3><p>{selected.email||selected.whatsapp||'—'}</p></div><button className="admin-btn admin-btn-icon" onClick={()=>setSelected(null)}>{I.close}</button></header><div className="inq-drawer-body">
      <div className="inq-section"><div className="inq-section-title">{zh?'联系方式':'Contact'}</div><div className="inq-info-grid"><div><small>Email</small><b>{selected.email||'—'}</b></div><div><small>WhatsApp</small><b>{selected.whatsapp||'—'}</b></div><div><small>{zh?'国家':'Country'}</small><b>{selected.country||'—'}</b></div><div><small>{zh?'来源':'Source'}</small><b>{selected.source||'website'}</b></div></div></div>
      <div className="inq-section"><div className="inq-section-title">{zh?'询盘内容':'Inquiry'}</div><div className="inq-message">{selected.message||'—'}</div></div>
      <div className="inq-section"><div className="inq-section-title">{zh?'销售状态':'Sales pipeline'}</div><div className="inq-edit-grid"><label><span>{zh?'阶段':'Stage'}</span><select className="admin-select" value={selected.lead_status||'new'} onChange={e=>patch({lead_status:e.target.value})}>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label><label><span>{zh?'优先级':'Priority'}</span><select className="admin-select" value={selected.priority||'medium'} onChange={e=>patch({priority:e.target.value})}>{PRIORITY.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></label></div></div>
      <div className="inq-section"><div className="inq-section-title">{zh?'跟进任务':'Follow-up'}</div><div className="inq-edit-grid"><label><span>{zh?'下次跟进时间':'Next follow-up'}</span><input className="admin-input" type="datetime-local" value={dtInput(selected.follow_up_at)} onChange={e=>patch({follow_up_at:e.target.value?new Date(e.target.value).toISOString():''})}/></label><label><span>{zh?'最近联系':'Last contact'}</span><input className="admin-input" type="datetime-local" value={dtInput(selected.last_contact_at)} onChange={e=>patch({last_contact_at:e.target.value?new Date(e.target.value).toISOString():''})}/></label></div></div>
      <div className="inq-section"><div className="inq-section-title">{zh?'销售备注':'Sales notes'}</div><textarea className="admin-input inq-notes" rows={5} value={selected.notes||''} onChange={e=>patch({notes:e.target.value})} placeholder={zh?'记录客户需求、预算、产量、采购时间等…':'Record requirements, budget, capacity, timeline…'}/></div>
      <div className="inq-section"><div className="inq-section-title">{zh?'邮件回复':'Reply by email'}</div><label><span>{zh?'邮件主题':'Subject'}</span><input className="admin-input" value={replySubject} onChange={e=>setReplySubject(e.target.value)}/></label><label style={{marginTop:8}}><span>{zh?'邮件内容':'Message'}</span><textarea className="admin-input inq-reply-box" rows={7} value={replyMessage} onChange={e=>setReplyMessage(e.target.value)} placeholder={zh?'输入给客户的回复…':'Write a reply to the customer…'}/></label><div className="inq-reply-meta">{zh?'发件地址由「邮件通知 → 发件人（From）」统一控制。':'Sender is controlled by Mail Notifications → From.'}</div><button className="admin-btn admin-btn-primary" style={{marginTop:10}} disabled={replying||!selected.email||!replyMessage.trim()} onClick={sendReply}>{replying?(zh?'发送中…':'Sending…'):(zh?'发送邮件并标记已回复':'Send & mark replied')}</button></div>
      <div className="inq-drawer-footer"><button className="admin-btn admin-btn-primary" onClick={saveDetail} disabled={saving}>{saving?(zh?'保存中…':'Saving…'):(zh?'保存询盘':'Save inquiry')}</button><button className="admin-btn" onClick={()=>setSelected(null)}>{zh?'关闭':'Close'}</button></div>
    </div></aside></div>}
  </div>;
}
